import {MigrationInterface, QueryRunner} from "typeorm";

export class initial1598553833992 implements MigrationInterface {
    name = 'initial1598553833992'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "attribute_type" ("type" text NOT NULL, CONSTRAINT "PK_629ff7618ae119c9081f463528b" PRIMARY KEY ("type"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "attribute_type_pk" ON "attribute_type" ("type") `);
        await queryRunner.query(`CREATE TABLE "factor" ("id" SERIAL NOT NULL, "classification1_id" integer NOT NULL, "classification2_id" integer NOT NULL, "name" character varying(5) NOT NULL, "description" character varying(255), "color" character varying(25) NOT NULL, CONSTRAINT "PK_474c0e9d4ca1c181f178952187d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "factor_ak_2" ON "factor" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "factor_pk" ON "factor" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "co_relation_uk" ON "factor" ("classification1_id", "classification2_id") `);
        await queryRunner.query(`CREATE TABLE "characteristic_type" ("type" text NOT NULL, "icon" text, CONSTRAINT "PK_cfe4cf9457327687d14bb551401" PRIMARY KEY ("type"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "characteristic_type_pk" ON "characteristic_type" ("type") `);
        await queryRunner.query(`CREATE TABLE "characteristic_alias" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, "characteristic_id" integer, CONSTRAINT "PK_5204654ee9810aa162325269c0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "characteristic_alias_ak_1" ON "characteristic_alias" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "characteristic_alias_pk" ON "characteristic_alias" ("id") `);
        await queryRunner.query(`CREATE TABLE "metric_alias" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, "metric_mineral_id" integer, CONSTRAINT "PK_4fa73ff2365884412d877d5fd52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_alias_ak_1" ON "metric_alias" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_alias_pk" ON "metric_alias" ("id") `);
        await queryRunner.query(`CREATE TABLE "metric" ("id" SERIAL NOT NULL, "name" character varying(30) NOT NULL, "description" character varying(100), CONSTRAINT "PK_7d24c075ea2926dd32bd1c534ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_ak_1" ON "metric" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_pk" ON "metric" ("id") `);
        await queryRunner.query(`CREATE TABLE "mineral" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, CONSTRAINT "PK_7163ddfaca3b9fc68b150c662cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "mineral_pk" ON "mineral" ("id") `);
        await queryRunner.query(`CREATE TABLE "metric_mineral" ("id" integer NOT NULL, "name" character varying(25) NOT NULL, "description" character varying(100), "unit_default" character varying(10) NOT NULL, "metric_id" integer NOT NULL, "mineral_id" integer, CONSTRAINT "PK_5de1eabeec2fb3e595cbfc8ea7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_mineral_ak_1" ON "metric_mineral" ("metric_id", "mineral_id", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_mineral_pk" ON "metric_mineral" ("id") `);
        await queryRunner.query(`CREATE TABLE "metric_characteristic" ("id" SERIAL NOT NULL, "characteristic_id" integer NOT NULL, "metric_mineral_id" integer, CONSTRAINT "UQ_cfaac0c5965a5ab455961e68e7a" UNIQUE ("metric_mineral_id"), CONSTRAINT "PK_3451878483516aeab0073afdfd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_characteristic_pk" ON "metric_characteristic" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_characteristic_ak_1" ON "metric_characteristic" ("characteristic_id", "metric_mineral_id") `);
        await queryRunner.query(`CREATE TABLE "characteristic" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, "description" character varying(100), "type" text, CONSTRAINT "PK_88f998ec743440a5c758e08ece4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "characteristic_ak_1" ON "characteristic" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "characteristic_pk" ON "characteristic" ("id") `);
        await queryRunner.query(`CREATE TABLE "time_unit" ("id" character(5) NOT NULL, "name" character varying(20) NOT NULL, "description" character varying(100), CONSTRAINT "PK_4496a64dfba20f0db0a2bb3aa1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "time_unit_pk" ON "time_unit" ("id") `);
        await queryRunner.query(`CREATE TABLE "space_time" ("id" SERIAL NOT NULL, "from" TIMESTAMP NOT NULL, "to" TIMESTAMP NOT NULL, "location_id" integer, "time_unit_id" character(5), CONSTRAINT "PK_9e452500bd8687f88660865887f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "space_time_pk" ON "space_time" ("id") `);
        await queryRunner.query(`CREATE TABLE "measure_detail" ("id" SERIAL NOT NULL, "value" real NOT NULL, "measure_id" integer NOT NULL, "classification_metric_id" integer NOT NULL, "equa_calc" character varying(100), CONSTRAINT "PK_fc63f70a313895363a1665495bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "measure_detail_pk" ON "measure_detail" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "measure_detail_ak_1" ON "measure_detail" ("classification_metric_id", "measure_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_pk" ON "users" ("id") `);
        await queryRunner.query(`CREATE TABLE "import_file" ("id" SERIAL NOT NULL, "file_name" text NOT NULL, "url" character varying(100) NOT NULL, "mime_type" character varying(100), "checksum" text NOT NULL, CONSTRAINT "PK_1c45e43598e6cde5b5934cfca7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "import_file_pk" ON "import_file" ("id") `);
        await queryRunner.query(`CREATE TABLE "import_status" ("status" text NOT NULL, CONSTRAINT "PK_76e6286de5544714fb09afc75a2" PRIMARY KEY ("status"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "import_status_pk" ON "import_status" ("status") `);
        await queryRunner.query(`CREATE TABLE "import" ("id" SERIAL NOT NULL, "name" text NOT NULL, "parameters" jsonb NOT NULL, "status_context" jsonb NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "status" text, "template_id" integer, "import_file_id" integer, "owner_id" integer, CONSTRAINT "REL_303047526a80afbfa9f2fb73f9" UNIQUE ("import_file_id"), CONSTRAINT "PK_4ed733f5bcc70cec27187bd90eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "import_pk" ON "import" ("id") `);
        await queryRunner.query(`CREATE TABLE "measure" ("id" SERIAL NOT NULL, "space_time_id" integer, "import_id" integer, CONSTRAINT "PK_ddc1ad2a86717cedc808809423e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "measure_pk" ON "measure" ("id") `);
        await queryRunner.query(`CREATE TABLE "measure_distinction" ("id" SERIAL NOT NULL, "measure_id" integer NOT NULL, "distinction_id" integer, "distinction_value_id" integer, CONSTRAINT "PK_67eaf90ae725c4043aa5fa2421d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "measure_distinction_pk" ON "measure_distinction" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "measure_descriptor_uk" ON "measure_distinction" ("distinction_id", "measure_id") `);
        await queryRunner.query(`CREATE TABLE "equation_value" ("id" SERIAL NOT NULL, "replace" character varying(5), "classification_metric1_id" integer NOT NULL, "classification_metric2_id" integer, "parameter_id" integer, CONSTRAINT "UQ_8fd7ecfee04229ca1a6b676a52e" UNIQUE ("classification_metric2_id"), CONSTRAINT "PK_3d7fa2303f846b98cbc172faac4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "equation_value_pk" ON "equation_value" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "equation_value_ak_1" ON "equation_value" ("classification_metric1_id", "classification_metric2_id") `);
        await queryRunner.query(`CREATE TABLE "parameter" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, CONSTRAINT "PK_cc5c047040f9c69f0e0d6a844a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "parameter_pk" ON "parameter" ("id") `);
        await queryRunner.query(`CREATE TABLE "parameter_value" ("id" SERIAL NOT NULL, "from" TIMESTAMP NOT NULL, "to" TIMESTAMP, "value" real NOT NULL, "distinction_id" integer, "location_id" integer, "parameter_id" integer, CONSTRAINT "PK_44821e6332d33d4958ceb24bf93" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "parameter_value_pk" ON "parameter_value" ("id") `);
        await queryRunner.query(`CREATE TABLE "distinction" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, "description" character varying(100), "characteristic_id" integer NOT NULL, "code" integer, CONSTRAINT "PK_5fd76ec4dafda2d27a08a3c3690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "distinction_pk" ON "distinction" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "distinction_idx_1" ON "distinction" ("characteristic_id", "code") `);
        await queryRunner.query(`CREATE TABLE "distinction_value" ("id" SERIAL NOT NULL, "start_date" TIMESTAMP NOT NULL DEFAULT now(), "end_date" TIMESTAMP, "value" jsonb NOT NULL, "distinction_id" integer, "location_id" integer, "metric_characteristic_id" integer, CONSTRAINT "PK_557cdafba5a76160f1cf363014b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "distinction_value_pk" ON "distinction_value" ("id") `);
        await queryRunner.query(`CREATE TABLE "location" ("id" SERIAL NOT NULL, "kml" integer, "name" character varying(20) NOT NULL, "description" character varying(100), "location_id" integer, "space_unit_id" integer NOT NULL, "value" jsonb, CONSTRAINT "PK_876d7bdba03c72251ec4c2dc827" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "location_ak_1" ON "location" ("location_id", "name") `);
        await queryRunner.query(`CREATE TABLE "space_unit_alias" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, "space_unit_id" integer, CONSTRAINT "PK_b11bb70fc8640dea7e85f2c6a35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "space_unit_alias_pk" ON "space_unit_alias" ("id") `);
        await queryRunner.query(`CREATE TABLE "space_unit" ("id" SERIAL NOT NULL, "name" character varying(20) NOT NULL, "description" character varying(100), "space_unit_id" integer, CONSTRAINT "PK_7c597329ee1c82ea5f49834aa51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "space_unit_ak_1" ON "space_unit" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "space_unit_pk" ON "space_unit" ("id") `);
        await queryRunner.query(`CREATE TABLE "template_type" ("type" text NOT NULL, CONSTRAINT "PK_b8fd7bfefde6ddb404faa414176" PRIMARY KEY ("type"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "template_type_pk" ON "template_type" ("type") `);
        await queryRunner.query(`CREATE TABLE "template" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, "parameters" jsonb NOT NULL, "type" text, "location_id" integer, "classification_id" integer, "space_unit_id" integer, CONSTRAINT "PK_fbae2ac36bd9b5e1e793b957b7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "template_pk" ON "template" ("id") `);
        await queryRunner.query(`CREATE TABLE "classification" ("id" integer NOT NULL, "name" character varying(25) NOT NULL, "abbreviation" character varying(10) NOT NULL, "color" character varying(25) NOT NULL, "group" boolean, "description" character varying(100), "classification_id" integer, CONSTRAINT "PK_1dc9176492b73104aa3d19ccff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "classification_pk" ON "classification" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "classification_ak_1" ON "classification" ("abbreviation") `);
        await queryRunner.query(`CREATE TABLE "classification_metric" ("id" integer NOT NULL, "classification_id" integer NOT NULL, "metric_mineral_id" integer NOT NULL, "equation" character varying(100), CONSTRAINT "PK_e5199e7551cb74baa1b8a3d29d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "classification_metric_pk" ON "classification_metric" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "classification_metric_ak_1" ON "classification_metric" ("classification_id", "metric_mineral_id") `);
        await queryRunner.query(`CREATE TABLE "metric_attribute" ("id" SERIAL NOT NULL, "attribute_id" integer NOT NULL, "classification_metric_id" integer NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_7eee85dd0c88f6791d03de88ae0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_attribute_pk" ON "metric_attribute" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "metric_attribute_ak_1" ON "metric_attribute" ("attribute_id", "classification_metric_id") `);
        await queryRunner.query(`CREATE TABLE "attribute" ("id" SERIAL NOT NULL, "name" character varying(25) NOT NULL, "description" character varying(100), "value" jsonb NOT NULL, "type" text, CONSTRAINT "PK_b13fb7c5c9e9dff62b60e0de729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "attribute_ak_1" ON "attribute" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "attribute_pk" ON "attribute" ("id") `);
        await queryRunner.query(`CREATE TABLE "company" ("id" SERIAL NOT NULL, "name" character varying(40) NOT NULL, "description" character varying(100), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "company_ak_1" ON "company" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "company_pk" ON "company" ("id") `);
        await queryRunner.query(`ALTER TABLE "factor" ADD CONSTRAINT "FK_92704f93014e955b062c10f0b37" FOREIGN KEY ("classification1_id") REFERENCES "classification"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "factor" ADD CONSTRAINT "FK_3f473384597d923f645b2a72498" FOREIGN KEY ("classification2_id") REFERENCES "classification"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "characteristic_alias" ADD CONSTRAINT "FK_3ba65dc1c329938f1693feb9417" FOREIGN KEY ("characteristic_id") REFERENCES "characteristic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_alias" ADD CONSTRAINT "FK_12a23de57d3d099a43fd749f9c4" FOREIGN KEY ("metric_mineral_id") REFERENCES "metric_mineral"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_mineral" ADD CONSTRAINT "FK_1ad9805277d9cb4ed7d64d471d9" FOREIGN KEY ("metric_id") REFERENCES "metric"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_mineral" ADD CONSTRAINT "FK_14759d2334ed742317f1d6a7687" FOREIGN KEY ("mineral_id") REFERENCES "mineral"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_characteristic" ADD CONSTRAINT "FK_de2d58635fc8e9d7e6a4c3b55ce" FOREIGN KEY ("characteristic_id") REFERENCES "characteristic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_characteristic" ADD CONSTRAINT "FK_cfaac0c5965a5ab455961e68e7a" FOREIGN KEY ("metric_mineral_id") REFERENCES "metric_mineral"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characteristic" ADD CONSTRAINT "FK_c829650a67cb5e15141c31ae9bc" FOREIGN KEY ("type") REFERENCES "characteristic_type"("type") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space_time" ADD CONSTRAINT "FK_447f54e1f9b58962e2f78c00117" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space_time" ADD CONSTRAINT "FK_a8f9bff8b6f8d2a7671852e2b66" FOREIGN KEY ("time_unit_id") REFERENCES "time_unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measure_detail" ADD CONSTRAINT "FK_2e7b9c4a4b1aa03a2d54cf45d4b" FOREIGN KEY ("classification_metric_id") REFERENCES "classification_metric"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measure_detail" ADD CONSTRAINT "FK_c8f3de7be2432c20821e504638f" FOREIGN KEY ("measure_id") REFERENCES "measure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import" ADD CONSTRAINT "FK_5a2edf3ad5874f6ef78fc8937bb" FOREIGN KEY ("status") REFERENCES "import_status"("status") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import" ADD CONSTRAINT "FK_09b63cb32c1a044054f4b57c198" FOREIGN KEY ("template_id") REFERENCES "template"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import" ADD CONSTRAINT "FK_303047526a80afbfa9f2fb73f97" FOREIGN KEY ("import_file_id") REFERENCES "import_file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import" ADD CONSTRAINT "FK_23c652da6e3c4cc7b29202282c8" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measure" ADD CONSTRAINT "FK_b5a5476e4c31efd6934146fd6ad" FOREIGN KEY ("space_time_id") REFERENCES "space_time"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measure" ADD CONSTRAINT "FK_07367ccda8637c515ccab6b4e35" FOREIGN KEY ("import_id") REFERENCES "import"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measure_distinction" ADD CONSTRAINT "FK_46a4049a20af8178308ab5f67b3" FOREIGN KEY ("distinction_id") REFERENCES "distinction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "measure_distinction" ADD CONSTRAINT "FK_99762f47ca43b2607488c666b59" FOREIGN KEY ("measure_id") REFERENCES "measure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equation_value" ADD CONSTRAINT "FK_88e555a84df6fb6a23c3b69890d" FOREIGN KEY ("classification_metric1_id") REFERENCES "classification_metric"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equation_value" ADD CONSTRAINT "FK_8fd7ecfee04229ca1a6b676a52e" FOREIGN KEY ("classification_metric2_id") REFERENCES "classification_metric"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equation_value" ADD CONSTRAINT "FK_50d028c7d7fa6dd13bc833f01f3" FOREIGN KEY ("parameter_id") REFERENCES "parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parameter_value" ADD CONSTRAINT "FK_f2b13fc6822f2c4d6c68c663e26" FOREIGN KEY ("distinction_id") REFERENCES "distinction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parameter_value" ADD CONSTRAINT "FK_33f0a569e80c34a4e2d778440eb" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parameter_value" ADD CONSTRAINT "FK_1b5c4f45015f1759b45920a4cfb" FOREIGN KEY ("parameter_id") REFERENCES "parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distinction" ADD CONSTRAINT "FK_823f3c253e3adbd5e6c39fcb964" FOREIGN KEY ("characteristic_id") REFERENCES "characteristic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distinction_value" ADD CONSTRAINT "FK_086fd248b8fee12bae1f301ad2c" FOREIGN KEY ("distinction_id") REFERENCES "distinction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distinction_value" ADD CONSTRAINT "FK_54e833973fd48cb741e45c949bb" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distinction_value" ADD CONSTRAINT "FK_3f4b843238cb3ca89320d859e4e" FOREIGN KEY ("metric_characteristic_id") REFERENCES "metric_characteristic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_b6e6c23b493859e5875de66c18d" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_717309513d9c995e569545b5f64" FOREIGN KEY ("space_unit_id") REFERENCES "space_unit"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "space_unit_alias" ADD CONSTRAINT "FK_74d3a39fffdd163ce6aebd6b42b" FOREIGN KEY ("space_unit_id") REFERENCES "space_unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space_unit" ADD CONSTRAINT "FK_0ad86646efebd360c70bd987692" FOREIGN KEY ("space_unit_id") REFERENCES "space_unit"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_96f38b63fca0acb1b3fc5220c5e" FOREIGN KEY ("type") REFERENCES "template_type"("type") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_f8b4eac09f6c45bdb5870fa3ad9" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_12c3c81a2f343f9224920fb38db" FOREIGN KEY ("classification_id") REFERENCES "classification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_6d2c805b3d2eb1fa6ebe2b867ca" FOREIGN KEY ("space_unit_id") REFERENCES "space_unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classification" ADD CONSTRAINT "FK_81140cafc4162a2c0c11aa9525f" FOREIGN KEY ("classification_id") REFERENCES "classification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classification_metric" ADD CONSTRAINT "FK_1ed903d7b247b9a648e9db15320" FOREIGN KEY ("classification_id") REFERENCES "classification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classification_metric" ADD CONSTRAINT "FK_efdea99d8cb31115a23d7d4c030" FOREIGN KEY ("metric_mineral_id") REFERENCES "metric_mineral"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_attribute" ADD CONSTRAINT "FK_62e3069425a689d9b2564f67be4" FOREIGN KEY ("classification_metric_id") REFERENCES "classification_metric"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_attribute" ADD CONSTRAINT "FK_e63676a6fec226caff3ea5029ae" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute" ADD CONSTRAINT "FK_0dbafd93b752dcf58fbd7caac64" FOREIGN KEY ("type") REFERENCES "attribute_type"("type") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attribute" DROP CONSTRAINT "FK_0dbafd93b752dcf58fbd7caac64"`);
        await queryRunner.query(`ALTER TABLE "metric_attribute" DROP CONSTRAINT "FK_e63676a6fec226caff3ea5029ae"`);
        await queryRunner.query(`ALTER TABLE "metric_attribute" DROP CONSTRAINT "FK_62e3069425a689d9b2564f67be4"`);
        await queryRunner.query(`ALTER TABLE "classification_metric" DROP CONSTRAINT "FK_efdea99d8cb31115a23d7d4c030"`);
        await queryRunner.query(`ALTER TABLE "classification_metric" DROP CONSTRAINT "FK_1ed903d7b247b9a648e9db15320"`);
        await queryRunner.query(`ALTER TABLE "classification" DROP CONSTRAINT "FK_81140cafc4162a2c0c11aa9525f"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_6d2c805b3d2eb1fa6ebe2b867ca"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_12c3c81a2f343f9224920fb38db"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_f8b4eac09f6c45bdb5870fa3ad9"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_96f38b63fca0acb1b3fc5220c5e"`);
        await queryRunner.query(`ALTER TABLE "space_unit" DROP CONSTRAINT "FK_0ad86646efebd360c70bd987692"`);
        await queryRunner.query(`ALTER TABLE "space_unit_alias" DROP CONSTRAINT "FK_74d3a39fffdd163ce6aebd6b42b"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_717309513d9c995e569545b5f64"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_b6e6c23b493859e5875de66c18d"`);
        await queryRunner.query(`ALTER TABLE "distinction_value" DROP CONSTRAINT "FK_3f4b843238cb3ca89320d859e4e"`);
        await queryRunner.query(`ALTER TABLE "distinction_value" DROP CONSTRAINT "FK_54e833973fd48cb741e45c949bb"`);
        await queryRunner.query(`ALTER TABLE "distinction_value" DROP CONSTRAINT "FK_086fd248b8fee12bae1f301ad2c"`);
        await queryRunner.query(`ALTER TABLE "distinction" DROP CONSTRAINT "FK_823f3c253e3adbd5e6c39fcb964"`);
        await queryRunner.query(`ALTER TABLE "parameter_value" DROP CONSTRAINT "FK_1b5c4f45015f1759b45920a4cfb"`);
        await queryRunner.query(`ALTER TABLE "parameter_value" DROP CONSTRAINT "FK_33f0a569e80c34a4e2d778440eb"`);
        await queryRunner.query(`ALTER TABLE "parameter_value" DROP CONSTRAINT "FK_f2b13fc6822f2c4d6c68c663e26"`);
        await queryRunner.query(`ALTER TABLE "equation_value" DROP CONSTRAINT "FK_50d028c7d7fa6dd13bc833f01f3"`);
        await queryRunner.query(`ALTER TABLE "equation_value" DROP CONSTRAINT "FK_8fd7ecfee04229ca1a6b676a52e"`);
        await queryRunner.query(`ALTER TABLE "equation_value" DROP CONSTRAINT "FK_88e555a84df6fb6a23c3b69890d"`);
        await queryRunner.query(`ALTER TABLE "measure_distinction" DROP CONSTRAINT "FK_99762f47ca43b2607488c666b59"`);
        await queryRunner.query(`ALTER TABLE "measure_distinction" DROP CONSTRAINT "FK_46a4049a20af8178308ab5f67b3"`);
        await queryRunner.query(`ALTER TABLE "measure" DROP CONSTRAINT "FK_07367ccda8637c515ccab6b4e35"`);
        await queryRunner.query(`ALTER TABLE "measure" DROP CONSTRAINT "FK_b5a5476e4c31efd6934146fd6ad"`);
        await queryRunner.query(`ALTER TABLE "import" DROP CONSTRAINT "FK_23c652da6e3c4cc7b29202282c8"`);
        await queryRunner.query(`ALTER TABLE "import" DROP CONSTRAINT "FK_303047526a80afbfa9f2fb73f97"`);
        await queryRunner.query(`ALTER TABLE "import" DROP CONSTRAINT "FK_09b63cb32c1a044054f4b57c198"`);
        await queryRunner.query(`ALTER TABLE "import" DROP CONSTRAINT "FK_5a2edf3ad5874f6ef78fc8937bb"`);
        await queryRunner.query(`ALTER TABLE "measure_detail" DROP CONSTRAINT "FK_c8f3de7be2432c20821e504638f"`);
        await queryRunner.query(`ALTER TABLE "measure_detail" DROP CONSTRAINT "FK_2e7b9c4a4b1aa03a2d54cf45d4b"`);
        await queryRunner.query(`ALTER TABLE "space_time" DROP CONSTRAINT "FK_a8f9bff8b6f8d2a7671852e2b66"`);
        await queryRunner.query(`ALTER TABLE "space_time" DROP CONSTRAINT "FK_447f54e1f9b58962e2f78c00117"`);
        await queryRunner.query(`ALTER TABLE "characteristic" DROP CONSTRAINT "FK_c829650a67cb5e15141c31ae9bc"`);
        await queryRunner.query(`ALTER TABLE "metric_characteristic" DROP CONSTRAINT "FK_cfaac0c5965a5ab455961e68e7a"`);
        await queryRunner.query(`ALTER TABLE "metric_characteristic" DROP CONSTRAINT "FK_de2d58635fc8e9d7e6a4c3b55ce"`);
        await queryRunner.query(`ALTER TABLE "metric_mineral" DROP CONSTRAINT "FK_14759d2334ed742317f1d6a7687"`);
        await queryRunner.query(`ALTER TABLE "metric_mineral" DROP CONSTRAINT "FK_1ad9805277d9cb4ed7d64d471d9"`);
        await queryRunner.query(`ALTER TABLE "metric_alias" DROP CONSTRAINT "FK_12a23de57d3d099a43fd749f9c4"`);
        await queryRunner.query(`ALTER TABLE "characteristic_alias" DROP CONSTRAINT "FK_3ba65dc1c329938f1693feb9417"`);
        await queryRunner.query(`ALTER TABLE "factor" DROP CONSTRAINT "FK_3f473384597d923f645b2a72498"`);
        await queryRunner.query(`ALTER TABLE "factor" DROP CONSTRAINT "FK_92704f93014e955b062c10f0b37"`);
        await queryRunner.query(`DROP INDEX "company_pk"`);
        await queryRunner.query(`DROP INDEX "company_ak_1"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP INDEX "attribute_pk"`);
        await queryRunner.query(`DROP INDEX "attribute_ak_1"`);
        await queryRunner.query(`DROP TABLE "attribute"`);
        await queryRunner.query(`DROP INDEX "metric_attribute_ak_1"`);
        await queryRunner.query(`DROP INDEX "metric_attribute_pk"`);
        await queryRunner.query(`DROP TABLE "metric_attribute"`);
        await queryRunner.query(`DROP INDEX "classification_metric_ak_1"`);
        await queryRunner.query(`DROP INDEX "classification_metric_pk"`);
        await queryRunner.query(`DROP TABLE "classification_metric"`);
        await queryRunner.query(`DROP INDEX "classification_ak_1"`);
        await queryRunner.query(`DROP INDEX "classification_pk"`);
        await queryRunner.query(`DROP TABLE "classification"`);
        await queryRunner.query(`DROP INDEX "template_pk"`);
        await queryRunner.query(`DROP TABLE "template"`);
        await queryRunner.query(`DROP INDEX "template_type_pk"`);
        await queryRunner.query(`DROP TABLE "template_type"`);
        await queryRunner.query(`DROP INDEX "space_unit_pk"`);
        await queryRunner.query(`DROP INDEX "space_unit_ak_1"`);
        await queryRunner.query(`DROP TABLE "space_unit"`);
        await queryRunner.query(`DROP INDEX "space_unit_alias_pk"`);
        await queryRunner.query(`DROP TABLE "space_unit_alias"`);
        await queryRunner.query(`DROP INDEX "location_ak_1"`);
        await queryRunner.query(`DROP TABLE "location"`);
        await queryRunner.query(`DROP INDEX "distinction_value_pk"`);
        await queryRunner.query(`DROP TABLE "distinction_value"`);
        await queryRunner.query(`DROP INDEX "distinction_idx_1"`);
        await queryRunner.query(`DROP INDEX "distinction_pk"`);
        await queryRunner.query(`DROP TABLE "distinction"`);
        await queryRunner.query(`DROP INDEX "parameter_value_pk"`);
        await queryRunner.query(`DROP TABLE "parameter_value"`);
        await queryRunner.query(`DROP INDEX "parameter_pk"`);
        await queryRunner.query(`DROP TABLE "parameter"`);
        await queryRunner.query(`DROP INDEX "equation_value_ak_1"`);
        await queryRunner.query(`DROP INDEX "equation_value_pk"`);
        await queryRunner.query(`DROP TABLE "equation_value"`);
        await queryRunner.query(`DROP INDEX "measure_descriptor_uk"`);
        await queryRunner.query(`DROP INDEX "measure_distinction_pk"`);
        await queryRunner.query(`DROP TABLE "measure_distinction"`);
        await queryRunner.query(`DROP INDEX "measure_pk"`);
        await queryRunner.query(`DROP TABLE "measure"`);
        await queryRunner.query(`DROP INDEX "import_pk"`);
        await queryRunner.query(`DROP TABLE "import"`);
        await queryRunner.query(`DROP INDEX "import_status_pk"`);
        await queryRunner.query(`DROP TABLE "import_status"`);
        await queryRunner.query(`DROP INDEX "import_file_pk"`);
        await queryRunner.query(`DROP TABLE "import_file"`);
        await queryRunner.query(`DROP INDEX "users_pk"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "measure_detail_ak_1"`);
        await queryRunner.query(`DROP INDEX "measure_detail_pk"`);
        await queryRunner.query(`DROP TABLE "measure_detail"`);
        await queryRunner.query(`DROP INDEX "space_time_pk"`);
        await queryRunner.query(`DROP TABLE "space_time"`);
        await queryRunner.query(`DROP INDEX "time_unit_pk"`);
        await queryRunner.query(`DROP TABLE "time_unit"`);
        await queryRunner.query(`DROP INDEX "characteristic_pk"`);
        await queryRunner.query(`DROP INDEX "characteristic_ak_1"`);
        await queryRunner.query(`DROP TABLE "characteristic"`);
        await queryRunner.query(`DROP INDEX "metric_characteristic_ak_1"`);
        await queryRunner.query(`DROP INDEX "metric_characteristic_pk"`);
        await queryRunner.query(`DROP TABLE "metric_characteristic"`);
        await queryRunner.query(`DROP INDEX "metric_mineral_pk"`);
        await queryRunner.query(`DROP INDEX "metric_mineral_ak_1"`);
        await queryRunner.query(`DROP TABLE "metric_mineral"`);
        await queryRunner.query(`DROP INDEX "mineral_pk"`);
        await queryRunner.query(`DROP TABLE "mineral"`);
        await queryRunner.query(`DROP INDEX "metric_pk"`);
        await queryRunner.query(`DROP INDEX "metric_ak_1"`);
        await queryRunner.query(`DROP TABLE "metric"`);
        await queryRunner.query(`DROP INDEX "metric_alias_pk"`);
        await queryRunner.query(`DROP INDEX "metric_alias_ak_1"`);
        await queryRunner.query(`DROP TABLE "metric_alias"`);
        await queryRunner.query(`DROP INDEX "characteristic_alias_pk"`);
        await queryRunner.query(`DROP INDEX "characteristic_alias_ak_1"`);
        await queryRunner.query(`DROP TABLE "characteristic_alias"`);
        await queryRunner.query(`DROP INDEX "characteristic_type_pk"`);
        await queryRunner.query(`DROP TABLE "characteristic_type"`);
        await queryRunner.query(`DROP INDEX "co_relation_uk"`);
        await queryRunner.query(`DROP INDEX "factor_pk"`);
        await queryRunner.query(`DROP INDEX "factor_ak_2"`);
        await queryRunner.query(`DROP TABLE "factor"`);
        await queryRunner.query(`DROP INDEX "attribute_type_pk"`);
        await queryRunner.query(`DROP TABLE "attribute_type"`);
    }

}
